## 00. PyTorch Fundemantals

In [ ]:
import torch
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
print(torch.__version__)

2.9.0+cpu


## Introduction to tensors

### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as Python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[1,2],
                       [3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([1, 2])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR[0][2]

tensor([7, 8, 9])

### Random Tensors

start with random numbers -> look at data -> update random numbers

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5981, 0.7196, 0.3526, 0.3496],
        [0.9784, 0.5373, 0.7777, 0.8581],
        [0.5185, 0.8990, 0.1969, 0.7284]])

### Zeros and ones

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### Creating a range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(0,11)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

default = float32

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device, işlem yaparken tensorlar aynı cihazda olmalı

In [ ]:
float_32_tensor = torch.tensor([3.0, 2.0, 1.0],
                               dtype=None, #datatype of tensor
                               device=None, #cpu or cuda, what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensor operations
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 2., 1.], dtype=torch.float16)

In [ ]:
float_32_tensor * float_16_tensor

tensor([9., 4., 1.])

### Getting informations from tensors

1.Tensors not right datatype -> `tensor.dtype`

2.Tensors not right shape -> `tensor.shape`

3.Tensors not on the right device -> `tensor.device`

In [ ]:
float_16_tensor.dtype, float_16_tensor.shape, float_16_tensor.device

(torch.float16, torch.Size([3]), device(type='cpu'))

In [ ]:
float_16_tensor.size()

torch.Size([3])

### Tensor operations

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10  #adding, subtracting, multiplying,(element-wise), division

tensor([11, 12, 13])

In [ ]:
torch.mul(tensor, 10)  #in-built funcitons

tensor([10, 20, 30])

### MATRIX MULTIPLICATION (dot product)

One of the most common errors in deep learning : shape errors

There are 2 main rules that performing matrix multiplicaiton needs to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(3,2) @ (2,3)` will work
* `(2,3) @ (3,2)` will work
2. The resulting matrix has the shape of **outer dimensions**:
* `(3,2) @ (2,3)` -> `(3,3)`

In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
tensor_A =  torch.tensor([[1,2],
              [3,4],
              [5,6]])

In [ ]:
tensor_B =  torch.tensor([[1,2],
              [3,4],
              [5,6]])

In [ ]:
torch.mm(tensor_A, tensor_B.T) # mm = matmul

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [ ]:
x = torch.arange(0,100,10)
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

Find the position in tensor that has the minimum value eith argmin -> returns index position

In [ ]:
x.argmin()

tensor(0)

### Reshaping, stacking, squeezing and unsqueezing

* Reshaping
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacing - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions to a target tensor
* Unsqueeze - add a `1` dimension toa target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(3,3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
z = x.view(3,3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [ ]:
# changing z changes x (because a view of tensor shares the same memory as the original)
z[:,0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [ ]:
x_stacked = torch.stack([x,x,x,x])
x_stacked

tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.],
        [5., 2., 3., 5., 5., 6., 5., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped = x_reshaped.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped.squeeze(), x_reshaped.squeeze().size()

(tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]), torch.Size([9]))

Örnek: (1, 3, 1) boyutunda bir tensör

x = torch.zeros(1, 3, 1)

Tüm 1'leri sil -> Sonuç: (3,)

y = torch.squeeze(x)

Sadece 0. boyutu sil -> Sonuç: (3, 1)

z = torch.squeeze(x, dim=0)

In [ ]:
# torch.unsqueeze - adds a single dimension to a target tensor at a specific dim (dimension)
x_reshaped.unsqueeze(dim=0), x_reshaped.unsqueeze(dim=0).shape

(tensor([[[5., 2., 3., 5., 5., 6., 5., 8., 9.]]]), torch.Size([1, 1, 9]))

In [ ]:
x_reshaped.unsqueeze(dim=2), x_reshaped.unsqueeze(dim=2).shape

(tensor([[[5.],
          [2.],
          [3.],
          [5.],
          [5.],
          [6.],
          [5.],
          [8.],
          [9.]]]),
 torch.Size([1, 9, 1]))

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
# permute is a view of ther original, they share the same address
x_original = torch.randn(size=(224,224,3))
x_permuted = x_original.permute(2,0,1)

x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [ ]:
x_original[0,0,0] = 15
x_original[0,0,0], x_permuted[0,0,0] # a view in pytorch

(tensor(15.), tensor(15.))

### INDEXING (selecting data from tensors)

Similar to indexing with NumPy

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][1] # dim=1

tensor([4, 5, 6])

In [ ]:
x[0][0][2] # last dimension

tensor(3)

In [ ]:
# you can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1] # get all values od 0th and 1st dimensions but only index 1 of 2nd dimension

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[0,1,1]

tensor(5)

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

## PyTorch tensors & NumPy
* Numpy array -> pytorch tensor  : `torch.from_numpy(ndarray)`
* PyTorch tensor -> numpy array : `torch.Tensor.numpy()`

In [ ]:
array = np.arange(1.0, 8.0)
# warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

 ## Reproducibility (trying to take random out of random)

 To reduce the randomness in neural networks and PyTorch comes the concepts of a **random seed** .




In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_A = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED) # her seferinde yazmak lazım
random_tensor_B = torch.rand(3,4)

random_tensor_A == random_tensor_B

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors and PyTorch objects on the GPUs (and making faster computations)
(CUDA + NVIDIA)

1. Easiest: Google Colab

2. Use your own GPU

3. Use cloud computing (GCP, AWS, Azure)  

In [ ]:
torch.cuda.is_available()

False

For PyTorch, since it's capable of runnig compute on the GPU or CPU, it's best practice to setup device agnostic code:
e.g. run on GPU if available, else default to CPU

In [ ]:
import torch
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
#move tensor to gpu (if available)
tensor = torch.tensor([1,2,3])
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

## Moving tensors back to CPU

NumPy can only work with CPU

If tensor is on the GPU, can't transform it to numpy.

`tensor_back_in_cpu = tensor_on_gpu.cpu().numpy()`

## EXERCISES

In [1]:
import torch
tensor_1 = torch.rand(7,7)
tensor_1

tensor([[0.8724, 0.5641, 0.2882, 0.9126, 0.6418, 0.3972, 0.0756],
        [0.7814, 0.0515, 0.7401, 0.6985, 0.1832, 0.5526, 0.6338],
        [0.2045, 0.9319, 0.1582, 0.0223, 0.9033, 0.9402, 0.5277],
        [0.9566, 0.1651, 0.7813, 0.2859, 0.3611, 0.4313, 0.6192],
        [0.0592, 0.4195, 0.7037, 0.8034, 0.3781, 0.6224, 0.3310],
        [0.8625, 0.0509, 0.7631, 0.9905, 0.5353, 0.8049, 0.0566],
        [0.6076, 0.9264, 0.6789, 0.4616, 0.5119, 0.7275, 0.2693]])

In [2]:
tensor_2 = torch.rand(1,7)
torch.mm(tensor_1, tensor_2.T)

tensor([[1.7238],
        [2.1632],
        [1.7200],
        [2.0042],
        [1.9871],
        [2.2949],
        [1.9726]])

In [7]:
RANDOM_SEED = 0

torch.manual_seed(RANDOM_SEED)
tensor_1 = torch.rand(7,7)


tensor_2 = torch.rand(1,7)

torch.mm(tensor_1, tensor_2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

In [2]:
import torch
torch.cuda.is_available()


True

In [3]:
torch.cuda.manual_seed(1234)

In [9]:
torch.manual_seed(1234)
device = "cuda" if torch.cuda.is_available else "cpu"
tensor_1 = torch.rand(2,3).to(device)
tensor_2 = torch.rand(2,3).to(device)
tensor_1, tensor_2

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [11]:
tensor_3 = torch.mm(tensor_1, tensor_2.T)
tensor_3

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

In [12]:
tensor_3.min()

tensor(0.3647, device='cuda:0')

In [13]:
tensor_3.argmin()

tensor(0, device='cuda:0')

In [14]:
torch.manual_seed(7)
tensor_4 = torch.rand(1,1,1,10)
print(tensor_4, tensor_4.shape)
tensor_5 = tensor_4.squeeze()
print(tensor_5, tensor_5.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
